### ISSUE TITLE
Feature request: Mirror features of similar, native streamlit components

### ISSUE THREAD

**Issue by ojwenzel** [blackary/streamlit-keyup#10]
First of all, thank you @blackary for sharing this feature! It is a very beautiful and productive extension to m streamlit apps!

In some of those apps it would be nice if st_keyup supported some of the features from similar streamlit components. In particular, I am thinking of the `label_visibility` and `placeholder` arguments of the [st.text_input](https://docs.streamlit.io/library/api-reference/widgets/st.text_input), but maybe there are more! Whats your take?

**Comment by blackary** [comment]
@ojwenzel That's a great idea! I'll work on adding those.

**Comment by blackary** [comment]
This will be released in version 0.2.0

**Comment by ojwenzel** [comment]
That was lightning fast. thx!
