### ISSUE TITLE
label and text box always white no matter the theme.

### ISSUE THREAD

**Issue by 3eeps** [blackary/streamlit-keyup#29]
hello! i believe the latest version has broke my app with this now rather ugly white text input box. changing themes does not help.

![image](https://github.com/blackary/streamlit-keyup/assets/55860052/6112f499-be89-4221-b95f-eb9084c73354)

any ideas i can try? ive uninstalled and reinstalled the latest version without avail.

**Comment by blackary** [comment]
Fixed by #31
