### ISSUE TITLE
pip install doesn't give usable library

### ISSUE THREAD

**Issue by keiranmraine** [blackary/streamlit-keyup#3]
Hi,

I'm finding that the import is not working.  I've tried a clean venv and what I see is the distribution is present `streamlit_keyup-0.1.4.dist-info` but appears to be unpacked to a generic `src` directory:

```
grep -c 'st-keyup component' .venv/lib/python3.10/site-packages/src/frontend/build/index.html
1
```

Thanks for any suggestions.

**Comment by blackary** [comment]
@keiranmraine Sorry about that -- if you install 0.1.5 that issue has been resolved. Thanks for pointing this out!

**Comment by keiranmraine** [comment]
Thanks, working as expected now.
