### ISSUE TITLE
streamlit-keyup no longer renders with Streamlit 1.32.2

### ISSUE THREAD

**Issue by nathancooperjones** [blackary/streamlit-keyup#35]
Streamlit 1.32.2 released on 3/14/24 and, with this release, a change was made such that streamlit-keyup no longer renders at all. 

I'll attach screenshots below with what renders on my screen with a variety of recent Streamlit releases with the following dummy app code:

```python
from st_keyup import st_keyup
import streamlit as st


st.write(st.__version__)

value = st_keyup(label='Enter a value')

st.write(value)
```

**Streamlit 1.31.0**: 
<img width="798" alt="Screenshot 2024-03-19 at 9 22 34 AM" src="https://github.com/blackary/streamlit-keyup/assets/31417712/1e3828c2-585c-49ca-9190-d334412deffb">

**Streamlit 1.32.0**: 
<img width="808" alt="Screenshot 2024-03-19 at 9 23 12 AM" src="https://github.com/blackary/streamlit-keyup/assets/31417712/9f22a3e2-f02d-4351-b9f9-94f14d6f5109">

**Streamlit 1.32.1**: 
<img width="797" alt="Screenshot 2024-03-19 at 9 23 37 AM" src="https://github.com/blackary/streamlit-keyup/assets/31417712/a9582072-e089-4c64-9d4f-8f895227b6c5">

**Streamlit 1.32.2**: 
<img width="931" alt="Screenshot 2024-03-19 at 9 24 08 AM" src="https://github.com/blackary/streamlit-keyup/assets/31417712/619aa7fe-e223-4b36-a283-e88fc4942bf9">

**Comment by msabramo** [comment]
I saw this too.

Great job tracking down which version caused the breakage!

I wonder if we can get even more info about the breakage by cloning Streamlit from git and using `git bisect` to find the exact commit that caused the breakage. That could be really helpful to @blackary in figuring out a fix.

**Comment by msabramo** [comment]
OK, I just did a `git bisect` and FWIW, it says that this is the Streamlit commit that broke things:

```
(.venv)
abramowi at Marcs-MBP-3 in ~/Code/OpenSource/streamlit (1.32.2.dev20240313~2)(bisect)
$ git bisect good
8de20441339a0e5232b32d60b66f76f0bcb5ee0b is the first bad commit
commit 8de20441339a0e5232b32d60b66f76f0bcb5ee0b
Author: Ken McGrady <ken.mcgrady@gmail.com>
Date:   Wed Mar 13 19:10:09 2024 -0700

    Fix initial iframe height for custom component (#8290)

    ## Describe your changes

    In 1.32.0, we introduced some changes to custom components that rendered
    an iframe of a certain height instead of a default of 0. This change
    ensures that when the `frameHeight` is `undefined`, it will use 0.

    ## GitHub Issue Link (if applicable)
    Closes #8285

    ## Testing Plan

    - Added a test to make sure it's set (and the Skeleton appears and
    disappears)

    ---

    **Contribution License Agreement**

    By submitting this pull request you agree that all contributions to this
    project are made under the Apache 2.0 license.

 .../CustomComponent/ComponentInstance.test.tsx     | 85 ++++++++++++++++++++++
 .../widgets/CustomComponent/ComponentInstance.tsx  | 36 ++++-----
 2 files changed, 98 insertions(+), 23 deletions(-)
```

**Comment by msabramo** [comment]
See https://github.com/blackary/streamlit-keyup/pull/37 for a possible fix, although I mostly just got lucky messing around and don't know if this is a proper fix.

**Comment by blackary** [comment]
Wow, @msabramo , thank you so much for tracking the issue down and adding a fix -- this is so helpful!

**Comment by msabramo** [comment]
Thank **you**, @blackary for sharing your work!
