### ISSUE TITLE
Can i achieve using streamlit-keyup dynamic image functionality where an image changes based on user interaction in a Streamlit application

### ISSUE THREAD

**Issue by sainisanjay** [blackary/streamlit-keyup#41]
@blackary, 
When the search bar is empty, the arrow icon in the right corner is grey (1st Image). As the user begins to type in the search bar, the arrow icon turns blue (2nd Image).

![Screenshot 2024-04-03 at 4 37 30 PM](https://github.com/blackary/streamlit-keyup/assets/25616511/37ed5a5d-6497-4b9d-a14b-8c05abc432fc)

![Screenshot 2024-04-03 at 4 54 33 PM](https://github.com/blackary/streamlit-keyup/assets/25616511/d91cbc3e-ce45-4144-a154-01b5bc75cfd9)

**Comment by blackary** [comment]
You can likely use this library and some CSS to accomplish that, but it is outside the scope of what this library does directly.
